[2024-08-07T14:00:15.476+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:00:15.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_anyone.plots manual__2024-08-07T13:58:39.342327+00:00 [queued]>
[2024-08-07T14:00:15.516+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_anyone.plots manual__2024-08-07T13:58:39.342327+00:00 [queued]>
[2024-08-07T14:00:15.517+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T14:00:15.574+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): plots> on 2024-08-07 13:58:39.342327+00:00
[2024-08-07T14:00:15.596+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:00:15.599+0000] {standard_task_runner.py:64} INFO - Started process 85 to run task
[2024-08-07T14:00:15.599+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_anyone', 'plots', 'manual__2024-08-07T13:58:39.342327+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/ETL_anyone.py', '--cfg-path', '/tmp/tmpz43o292e']
[2024-08-07T14:00:15.603+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask plots
[2024-08-07T14:00:15.697+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_anyone.plots manual__2024-08-07T13:58:39.342327+00:00 [running]> on host 2e8a41f9b15c
[2024-08-07T14:00:15.881+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_anyone' AIRFLOW_CTX_TASK_ID='plots' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T13:58:39.342327+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T13:58:39.342327+00:00'
[2024-08-07T14:00:15.885+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:00:15.910+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:00:15.911+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/plots_dag.py", line 3, in main_plots_dag
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-08-07T14:00:15.983+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL_anyone, task_id=plots, run_id=manual__2024-08-07T13:58:39.342327+00:00, execution_date=20240807T135839, start_date=20240807T140015, end_date=20240807T140015
[2024-08-07T14:00:16.036+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task plots (No module named 'matplotlib'; 85)
[2024-08-07T14:00:16.056+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T14:00:16.091+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:00:16.123+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
